---
title: "Final project"
output: html_document
date: '2023-04-24'
---

```{r}
library(fpp3)
data <- read.csv("data.csv")
attach(data)
```

## Plot data
```{r}
head(data)
#plot(data, ylab = "Temperature anomaly (with respect to base anomaly", type = "l")

#x <- ts(data$Value, start = 1850, end = 2022) 
#head(data.ts)
#Years <- c(1850:2022)
data.ts <- data|>
  as_tsibble(index= Year)
data.ts |>
  autoplot()
```

##Transformation

```{r}
lambda <- data.ts |>
  features(Value, features = guerrero) |>
  pull(lambda_guerrero)
lambda

data.ts |>
  autoplot(box_cox(Value, lambda))

data.tsBC <- data.ts|>
  mutate(ValueBC = box_cox(Value,lambda))

```



## Descriptive statistics 

```{r}
summary(data)
data.ts |>
  features(Value, unitroot_ndiffs)
data.tsBC |>
  features(ValueBC, unitroot_ndiffs)
## Permateau test
```





## Make data stationary
```{r}
diff <- diff(Value)
plot(diff, type = "l")
```

## ACF

```{r}
data.ts |> ACF(Value) |>
  autoplot()
## Not seasonal they are annual, so they are highly autocorrelated.
data.ts |> PACF(Value) |>
  autoplot()

data.ts |> ACF(difference(Value)) |>
  autoplot()
data.ts |> PACF(difference(Value)) |>
  autoplot()
```

## ARIMA model

```{r}
fit <- data.ts |>
  model(arima1c = ARIMA(Value ~ 1 + pdq(1,1,3)),
        arima510c = ARIMA(Value ~ 1 + pdq(5,1,0)),
        arima0118c = ARIMA(Value ~ 1 +  pdq(0,1,18)),
        arima1 = ARIMA(Value ~ 0 + pdq(1,1,3)),
        arima510 = ARIMA(Value ~ 0+ pdq(5,1,0)),
        arima0118 = ARIMA(Value ~ 0 + pdq(0,1,18)),
        stepwise = ARIMA(Value),
        search = ARIMA(Value, stepwise = FALSE)
        )
fit |> report()
fit |>
  select(arima1c) |>
  report()

fit |>
  select(stepwise) |>
  report()

fit |>
  select(search) |>
  report()

fit2 <- data.ts |>
  model(stepwise1 = ARIMA(Value),
         search1 = ARIMA(Value, stepwise = FALSE))

fit2 |>
  select(search1) |>
  gg_tsresiduals()

#glance(fit) |> arrange(AICc) |> select(.model:BIC)

#fit <- data.ts %>%
 # model(ARIMA(Value))

#fit |>
 # select(search) |>
#  gg_tsresiduals()

#fit |>
 # filter(.model == 'search')

#glance(fit) %>% arrange(AICc) %>% select (.model:BIC)

```

## Forecasting

```{r}
all_forecast <- fit %>% forecast(h=30) %>% autoplot(data.ts)
all_forecast
```

```{r}
stepwiseforecast <- fit |>
  forecast(h=30) |>
  filter(.model=='stepwise') |>
  autoplot(data.ts)
stepwiseforecast
## TEST DATA
```

```{r}
data.ts_stl <- data.ts |>
  model(stl = STL(Value))
data.ts_stl |>
  components() |>
  autoplot()
```

```{r}
data.ts_stl |>
  generate(new_data = data.ts, times = 10,
           bootstrap_block_size = 8) |>
  autoplot(.sim) +
  autolayer(data.ts, Value) +
  guides(colour = "none") +
  labs(title = "Anomolies: Bootstrapped series",
       y="Anomolies in Celsius")
```

```{r}
sim <- data.ts_stl |>
  generate(new_data = data.ts, times = 100,
           bootstrap_block_size = 8) |>
  select(-.model, -Value)
ets_forecasts <- sim |>
  model(ets = ETS(.sim)) |>
  forecast(h = 30)
ets_forecasts |>
  update_tsibble(key = .rep) |>
  autoplot(.mean) +
  autolayer(data.ts, Value) +
  guides(colour = "none") +
  labs(title = "Anomolies: bootstrapped forecasts",
       y="Anomolies degrees Celsius")
```

```{r}
bagged <- ets_forecasts |>
  summarise(bagged_mean = mean(.mean))
data.ts |>
  model(ets = ETS(Value)) |>
  forecast(h = 30) |>
  autoplot(data.ts) +
  autolayer(bagged, bagged_mean, col = "#D55E00") +
  labs(title = "Anomolies: bootstrapped forecasts",
       y="Anomolies (degrees Celsius)")
```